# .github/workflows/deploy.yml

name: Deploy and Debug

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env

      # --- ДОБАВЛЯЕМ ШАГ ДЛЯ ПРОСМОТРА ФАЙЛОВ ---
      - name: List files for debugging
        run: ls -la

      - name: Build project
        run: npm run build

      # --- НОВЫЙ ШАГ: ЗАГРУЗКА РЕЗУЛЬТАТА СБОРКИ ---
      - name: Upload artifact for inspection
        uses: actions/upload-artifact@v3
        with:
          name: dist-files # Имя архива
          path: dist/      # Путь к папке, которую нужно заархивировать

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist 